/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;


import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.NurseOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientTreatmentWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author rutugawad
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    //private Map<PatientTreatmentWorkRequest, LabTestWorkRequest> patientToLab = new HashMap<>();

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization organization, Enterprise enterprise) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.doctorOrganization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        lblValue.setText(enterprise.getName());
        populateRequestTable();
    }

    public void populateRequestTable() {

        DefaultTableModel model = (DefaultTableModel) tblWorkRequest1.getModel();

        model.setRowCount(0);

        for (WorkRequest request : doctorOrganization.getWorkQueue().getWorkRequests()) {
            Object[] row = new Object[8];
            row[0] = ((PatientTreatmentWorkRequest) request).getRegistrationDate();
            row[1] = String.valueOf(((PatientTreatmentWorkRequest) request).getPatient().getId());
            row[2] = ((PatientTreatmentWorkRequest) request).getPatient().getFirstName() + " " + ((PatientTreatmentWorkRequest) request).getPatient().getLastName();
            row[3] = ((PatientTreatmentWorkRequest) request);
            row[4] = ((PatientTreatmentWorkRequest) request).getAssignedDoctor();
            row[5] = ((PatientTreatmentWorkRequest) request).getLabAssistant();
            row[6] = ((PatientTreatmentWorkRequest) request).getLabResult();
            row[7] = request.getStatus();

            model.addRow(row);

        }
        
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblWorkRequest1.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequestLab = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        lblMedicalTestWorkQueue = new javax.swing.JLabel();
        btnAssignToMe = new javax.swing.JButton();
        btnPrescribe = new javax.swing.JButton();
        btnTreated = new javax.swing.JButton();
        btnViewPatient = new javax.swing.JButton();
        lblWorkAreaForDoctors = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWorkRequest1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(173, 234, 203));
        setLayout(null);

        btnRequestLab.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnRequestLab.setText("Request Lab Test");
        btnRequestLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestLabActionPerformed(evt);
            }
        });
        add(btnRequestLab);
        btnRequestLab.setBounds(391, 358, 158, 32);

        lblEnterprise.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise :");
        add(lblEnterprise);
        lblEnterprise.setBounds(99, 57, 132, 30);

        lblValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValue.setText("<value>");
        add(lblValue);
        lblValue.setBounds(237, 59, 158, 26);

        lblMedicalTestWorkQueue.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        lblMedicalTestWorkQueue.setText("Medical Test Work Queue");
        add(lblMedicalTestWorkQueue);
        lblMedicalTestWorkQueue.setBounds(457, 101, 140, 15);

        btnAssignToMe.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnAssignToMe.setText("Assign To Me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });
        add(btnAssignToMe);
        btnAssignToMe.setBounds(233, 358, 126, 32);

        btnPrescribe.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnPrescribe.setText("Provide Prescription");
        btnPrescribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescribeActionPerformed(evt);
            }
        });
        add(btnPrescribe);
        btnPrescribe.setBounds(583, 358, 190, 32);

        btnTreated.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnTreated.setText("Complete Treatment");
        btnTreated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreatedActionPerformed(evt);
            }
        });
        add(btnTreated);
        btnTreated.setBounds(791, 357, 174, 35);

        btnViewPatient.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnViewPatient.setText("View Patient");
        btnViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientActionPerformed(evt);
            }
        });
        add(btnViewPatient);
        btnViewPatient.setBounds(89, 358, 126, 32);

        lblWorkAreaForDoctors.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblWorkAreaForDoctors.setForeground(new java.awt.Color(204, 0, 0));
        lblWorkAreaForDoctors.setText("WORK-AREA FOR DOCTOR");
        add(lblWorkAreaForDoctors);
        lblWorkAreaForDoctors.setBounds(424, 20, 220, 21);

        tblWorkRequest1.setBackground(new java.awt.Color(206, 255, 235));
        tblWorkRequest1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        tblWorkRequest1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Registration Date", "Patient Id", "Patient Name", "Illness", "Assigned Doctor", "Lab Assistant", "Lab Result", "Treatment Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblWorkRequest1);

        add(jScrollPane2);
        jScrollPane2.setBounds(89, 122, 870, 187);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doctor2image.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(100, 400, 1020, 270);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestLabActionPerformed

        int selectedRow = tblWorkRequest1.getSelectedRow();
        PatientTreatmentWorkRequest workRequest;

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        } else {
            workRequest = (PatientTreatmentWorkRequest) tblWorkRequest1.getValueAt(selectedRow, 3);
            if (workRequest.getAssignedDoctor() != null) {
                if (userAccount.equals(workRequest.getAssignedDoctor())) {
                    if (workRequest.getStatus().equalsIgnoreCase("Under Consultation")) {

                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        userProcessContainer.add("RequestLabTestJPanel", new RequestLabTestJPanel(userProcessContainer, userAccount, enterprise, workRequest));
                        layout.next(userProcessContainer);
                    } else {
                        JOptionPane.showMessageDialog(null, "Can not create the Lab request as the current status is " + workRequest.getStatus());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Not Authorised");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please assign the request first");
            }
        }


    }//GEN-LAST:event_btnRequestLabActionPerformed

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed

        int selectedRow = tblWorkRequest1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        } else {

            WorkRequest patientTreatmentWorkRequest = (PatientTreatmentWorkRequest) tblWorkRequest1.getValueAt(selectedRow, 3);
            if (((PatientTreatmentWorkRequest) patientTreatmentWorkRequest).getAssignedDoctor() == null) {

                if (patientTreatmentWorkRequest.getStatus().equalsIgnoreCase("Waiting for Doctor")) {
                    //patientTreatmentWorkRequest.setReceiver(userAccount);
                    ((PatientTreatmentWorkRequest) patientTreatmentWorkRequest).setAssignedDoctor(userAccount);
                    patientTreatmentWorkRequest.setStatus("Under Consultation");
                    populateRequestTable();
                    JOptionPane.showMessageDialog(null, "Success !! Request is assigned to you ");
                } else {
                    JOptionPane.showMessageDialog(null, "Cannot assign this patient as its current state is: " + patientTreatmentWorkRequest.getStatus());
                }

            } else {
                if(userAccount.equals(((PatientTreatmentWorkRequest) patientTreatmentWorkRequest).getAssignedDoctor())) {
                 JOptionPane.showMessageDialog(null, "Request is already assigned to you");
                } else {
                    JOptionPane.showMessageDialog(null, "Not Authorized");
                }
            }
        }
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientActionPerformed
        int selectedRow = tblWorkRequest1.getSelectedRow();
        PatientTreatmentWorkRequest patientWorkRequest;

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        } else {
            patientWorkRequest = (PatientTreatmentWorkRequest) tblWorkRequest1.getValueAt(selectedRow, 3);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("ViewPatientJPanel", new ViewPatientJPanel(userProcessContainer, userAccount, enterprise, patientWorkRequest));
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewPatientActionPerformed

    private void btnPrescribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescribeActionPerformed
        int selectedRow = tblWorkRequest1.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(null, "Please select a row");
        return;
    }

    PatientTreatmentWorkRequest request = (PatientTreatmentWorkRequest) tblWorkRequest1.getValueAt(selectedRow, 3);

    if (request.getAssignedDoctor() != null && userAccount.equals(request.getAssignedDoctor())) {
        if (request.getStatus().equalsIgnoreCase("Lab Test is Completed") || request.getStatus().equalsIgnoreCase("Under Consultation")) {
            // Update prescription and status
            request.setPrescription("Prescription details here");  // Replace with actual prescription input
            request.setStatus("Prescription Provided");

            // Add request to NurseOrganization's WorkQueue
            for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof NurseOrganization) {
                    org.getWorkQueue().getWorkRequests().add(request);
                    break;
                }
            }

            JOptionPane.showMessageDialog(null, "Prescription provided and request forwarded to Nurse.");
            populateRequestTable();
        } else {
            JOptionPane.showMessageDialog(null, "Cannot prescribe. Current status: " + request.getStatus());
        }
    } else {
        JOptionPane.showMessageDialog(null, "Not authorized to prescribe for this patient.");
    }
    }//GEN-LAST:event_btnPrescribeActionPerformed

    private void btnTreatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreatedActionPerformed
        int selectedRow = tblWorkRequest1.getSelectedRow();
        PatientTreatmentWorkRequest workRequest;

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        } else {
            workRequest = (PatientTreatmentWorkRequest) tblWorkRequest1.getValueAt(selectedRow, 3);
            if(workRequest.getAssignedDoctor() != null)
            {
            if (userAccount.equals(workRequest.getAssignedDoctor())) {
                if (workRequest.getStatus().equalsIgnoreCase("Prescription Provided")) {

                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    userProcessContainer.add("RequestBillingJPanel", new RequestBillingJPanel(userProcessContainer, userAccount, enterprise, workRequest));
                    workRequest.getPatient().setIsTreatmentComplete(true);
                    layout.next(userProcessContainer);
                } else {
                    if(workRequest.getStatus().equalsIgnoreCase("Consultation Completed"))
                    {
                        JOptionPane.showMessageDialog(null, "Treatment is already complete!");
                    }
                    else
                    {
                    JOptionPane.showMessageDialog(null, "Cannot complete the treatment. Please provide Prescription first!");
                }
                }
            } else {

                JOptionPane.showMessageDialog(null, "Not Authorised");
            }
        }
            else {
                JOptionPane.showMessageDialog(null, "Please assign the request first");
            }
        }
    }//GEN-LAST:event_btnTreatedActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnPrescribe;
    private javax.swing.JButton btnRequestLab;
    private javax.swing.JButton btnTreated;
    private javax.swing.JButton btnViewPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblMedicalTestWorkQueue;
    private javax.swing.JLabel lblValue;
    private javax.swing.JLabel lblWorkAreaForDoctors;
    private javax.swing.JTable tblWorkRequest1;
    // End of variables declaration//GEN-END:variables
}
