/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.AccountantOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AccountantBillingRequest;
import Business.WorkQueue.PatientTreatmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author VIRAJ
 */
public class RequestBillingJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private PatientTreatmentWorkRequest patientTreatmentWorkRequest;
    private EcoSystem ecoSystem;
    private double consultationCharges = 50;

    /**
     * Creates new form RequestBillingJPanel
     */
    RequestBillingJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, PatientTreatmentWorkRequest workRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.patientTreatmentWorkRequest = workRequest;
        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBillingRequest = new javax.swing.JLabel();
        lblPatientInfo = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblAssignedDoctor = new javax.swing.JLabel();
        txtAssignedDoctor = new javax.swing.JTextField();
        lblPatientId = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtConsultationFees = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        txtMedicationFees = new javax.swing.JTextField();
        jLabel113 = new javax.swing.JLabel();
        txtLabFees = new javax.swing.JTextField();
        jLabel123 = new javax.swing.JLabel();
        txtMiscellaneousFees = new javax.swing.JTextField();
        btnRequestBill = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lblBillingRequest.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblBillingRequest.setForeground(new java.awt.Color(204, 0, 0));
        lblBillingRequest.setText("BILLING REQUEST");
        add(lblBillingRequest);
        lblBillingRequest.setBounds(320, 20, 250, 28);

        lblPatientInfo.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblPatientInfo.setText("PATIENT INFORMATION");
        add(lblPatientInfo);
        lblPatientInfo.setBounds(10, 70, 170, 20);

        txtFirstName.setEditable(false);
        add(txtFirstName);
        txtFirstName.setBounds(200, 122, 131, 23);

        lblFirstName.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblFirstName.setText("First Name :");
        add(lblFirstName);
        lblFirstName.setBounds(90, 120, 90, 20);

        lblLastName.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblLastName.setText("Last Name :");
        add(lblLastName);
        lblLastName.setBounds(357, 120, 80, 15);

        txtLastName.setEditable(false);
        add(txtLastName);
        txtLastName.setBounds(450, 120, 131, 23);

        lblAssignedDoctor.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblAssignedDoctor.setText("Assigned Doctor :");
        add(lblAssignedDoctor);
        lblAssignedDoctor.setBounds(50, 160, 130, 15);

        txtAssignedDoctor.setEditable(false);
        add(txtAssignedDoctor);
        txtAssignedDoctor.setBounds(200, 160, 130, 23);

        lblPatientId.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblPatientId.setText("Patient Id:");
        add(lblPatientId);
        lblPatientId.setBounds(357, 160, 80, 15);

        txtPatientId.setEditable(false);
        add(txtPatientId);
        txtPatientId.setBounds(450, 160, 131, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("BILLING INFORMATION");
        add(jLabel3);
        jLabel3.setBounds(10, 210, 150, 20);

        jLabel43.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel43.setText("Consultaion Charges (USD) :");
        add(jLabel43);
        jLabel43.setBounds(10, 250, 200, 30);

        txtConsultationFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultationFeesActionPerformed(evt);
            }
        });
        txtConsultationFees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConsultationFeesKeyTyped(evt);
            }
        });
        add(txtConsultationFees);
        txtConsultationFees.setBounds(240, 250, 150, 30);

        jLabel53.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel53.setText("Medication Charges (USD):");
        add(jLabel53);
        jLabel53.setBounds(30, 310, 180, 30);

        txtMedicationFees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedicationFeesKeyTyped(evt);
            }
        });
        add(txtMedicationFees);
        txtMedicationFees.setBounds(240, 310, 150, 30);

        jLabel113.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel113.setText("Lab Test Charges (USD) :");
        add(jLabel113);
        jLabel113.setBounds(40, 280, 180, 30);

        txtLabFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLabFeesActionPerformed(evt);
            }
        });
        txtLabFees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLabFeesKeyTyped(evt);
            }
        });
        add(txtLabFees);
        txtLabFees.setBounds(240, 280, 150, 30);

        jLabel123.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel123.setText("Miscellaneous Charges (USD):");
        add(jLabel123);
        jLabel123.setBounds(10, 340, 210, 20);

        txtMiscellaneousFees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMiscellaneousFeesKeyTyped(evt);
            }
        });
        add(txtMiscellaneousFees);
        txtMiscellaneousFees.setBounds(240, 340, 150, 30);

        btnRequestBill.setBackground(new java.awt.Color(0, 153, 255));
        btnRequestBill.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnRequestBill.setText("Send Billing Request");
        btnRequestBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestBillActionPerformed(evt);
            }
        });
        add(btnRequestBill);
        btnRequestBill.setBounds(10, 390, 180, 40);

        btnBack.setBackground(new java.awt.Color(255, 0, 51));
        btnBack.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(30, 20, 90, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/billNew.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLabFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLabFeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLabFeesActionPerformed

    private void txtConsultationFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultationFeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultationFeesActionPerformed

    private void btnRequestBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestBillActionPerformed
//        String consultationCharge = txtConsultationFees.getText().trim();
//        String labChargesStr = txtLabFees.getText();
//        String miscellaneouschargesStr = txtMiscellaneousFees.getText();
//        String medicationChargesStr = txtMedicationFees.getText();
        if (txtConsultationFees.getText().trim().isEmpty()|| txtLabFees.getText().trim().isEmpty() || txtMiscellaneousFees.getText().trim().isEmpty() || txtMedicationFees.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory.");
        } else {
            
            
            double labCharges = Double.parseDouble(txtLabFees.getText());
            double miscellaneouscharges = Double.parseDouble(txtMiscellaneousFees.getText());
            double medicationCharges = Double.parseDouble(txtMedicationFees.getText().trim());
            double billingAmount = labCharges + consultationCharges + medicationCharges + miscellaneouscharges;
            //request.setBillAmount(billingAmount);

            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                patientTreatmentWorkRequest.setStatus("Consultation Completed");

                AccountantBillingRequest accountantBillingRequest = new AccountantBillingRequest();
                accountantBillingRequest.setBill(billingAmount);
                //  accountantBillingRequest.setPatientId(Integer.parseInt(txtPatientId.getText()));

                accountantBillingRequest.setSender(userAccount);
                accountantBillingRequest.setStatus("Sent");
                accountantBillingRequest.setPatient(patientTreatmentWorkRequest.getPatient());

                Organization org = null;
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizations()) {
                    if (organization instanceof AccountantOrganization) {
                        org = organization;
                        break;
                    }
                }
                if (org != null) {
                    org.getWorkQueue().getWorkRequests().add(accountantBillingRequest);
                    userAccount.getWorkQueue().getWorkRequests().add(accountantBillingRequest);
                }

                JOptionPane.showMessageDialog(null, "Prescription submitted successfully");
                btnRequestBill.setEnabled(false);
            }
        }

    }//GEN-LAST:event_btnRequestBillActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtConsultationFeesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultationFeesKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtConsultationFeesKeyTyped

    private void txtLabFeesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLabFeesKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtLabFeesKeyTyped

    private void txtMedicationFeesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicationFeesKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtMedicationFeesKeyTyped

    private void txtMiscellaneousFeesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMiscellaneousFeesKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtMiscellaneousFeesKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel lblAssignedDoctor;
    private javax.swing.JLabel lblBillingRequest;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPatientInfo;
    private javax.swing.JTextField txtAssignedDoctor;
    private javax.swing.JTextField txtConsultationFees;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLabFees;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMedicationFees;
    private javax.swing.JTextField txtMiscellaneousFees;
    private javax.swing.JTextField txtPatientId;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {

        txtFirstName.setText(patientTreatmentWorkRequest.getPatient().getFirstName());
        txtLastName.setText(patientTreatmentWorkRequest.getPatient().getLastName());
        txtPatientId.setText(String.valueOf(patientTreatmentWorkRequest.getPatient().getId()));
        txtAssignedDoctor.setText(patientTreatmentWorkRequest.getAssignedDoctor().getEmployee().getEmployeename());
        txtConsultationFees.setText(String.valueOf(consultationCharges));

    }
}
